name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa uma vez por dia à meia-noite (UTC)
  workflow_dispatch: # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: diogonascimentonovo
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit e push da animação
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdir -p output
          mv dist/github-contribution-grid-snake.svg output/
          git add output/github-contribution-grid-snake.svg
          git commit -m "Atualizando a cobrinha"
          git push
