name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite (UTC)
  workflow_dispatch: # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: diogonascimentonovo
          outputs: |
            dist/github-snake.svg

      - name: Criar diretório de saída
        run: mkdir -p output

      - name: Mover arquivo gerado para a pasta correta
        run: mv github-snake.svg output/github-snake.svg

      - name: Commit e push da animação
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/github-snake.svg
          git commit -m "Atualizando a cobrinha"
          git push
